### ISSUE TITLE
Windows XP

### ISSUE THREAD

**Issue by zer0cat** [zodiacon/sysrun#2]
Hello
this program return access denied in Windows XP. In Vista+ works good.
Why?

**Comment by zodiacon** [comment]
I don't know. I never tested it on XP.
I don't even have an XP around.

**Comment by zer0cat** [comment]
Ok, sorry. I have such code , it good works in Vista+, but dont works in XP. https://github.com/zer0cat/sys/blob/master/sys.c
And your code too. DuplicateTokenEx return access_denied..
I always thought XP was easy for security, but no.

**Comment by zer0cat** [comment]
Sorry for the annoying.. I research how to run in NT5 (even in Windows 2000) without a service, just copy the token! It works in NT5, if you interest, see my source: https://github.com/zer0cat/sys/blob/master/sys.c

**Comment by zodiacon** [comment]
Thanks!
